# Generated by Django 5.0.6 on 2024-08-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(max_length=2000),
        ),
    ]
