# Generated by Django 5.0.6 on 2024-08-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='cgpa',
            field=models.FloatField(default=0, max_length=200),
        ),
    ]
